# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6OwWFfdI3Z08FrjtRRQdAFOEyFDXDZw
"""

# app.py
import streamlit as st
import numpy as np
import joblib

# Load model and scaler
model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Game of Thrones Character Survival Predictor")

st.write("Input the character's features:")

# Replace these with your actual features and ranges
gender = st.selectbox("Gender (0 = Female, 1 = Male)", [0, 1])
book_count = st.slider("Books Appeared In", 0, 5, 1)
house = st.number_input("House (Encoded)", min_value=0, max_value=50, step=1)
nobility = st.selectbox("Nobility (0 = No, 1 = Yes)", [0, 1])
popularity = st.slider("Popularity Score", 0.0, 1.0, 0.5)

features = np.array([[gender, book_count, house, nobility, popularity]])
features_scaled = scaler.transform(features)

if st.button("Predict"):
    prediction = model.predict(features_scaled)[0]
    st.success("Prediction: **Alive**" if prediction == 1 else "Prediction: **Dead**")